version: "3"

services:
  db:
    image: postgres
    #restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
       - ./db:/docker-entrypoint-initdb.d
    ports:
      - "1234:5432" # host:container

  api:
    build: ./api
    environment:
      - PGUSER=postgres 
      - PGHOST=db
      - PGPASSWORD=password 
      - PGDATABASE=postgres 
      - PGPORT=5432 
      - PORT=8000
      - COOKIE_SECRET=secret
    ports:
      - "8000:8000"
    depends_on:
      - db
